version: "3"
services:
  server:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    volumes:
      - .:/code
    restart: always
    command: "node build/server.js"
    ports:
      - "9999:3000"
    networks:
      - knowledge.uz

networks:
  knowledge.uz:
