version: "3"
services:
  server:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    restart: always
    ports:
      - "9999:80"
    networks:
      - knowledge.uz

networks:
  knowledge.uz:
